# Generated by Django 5.2.3 on 2025-06-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Max 30 characters. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True),
        ),
    ]
