# Generated by Django 5.2.3 on 2025-07-03 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_actionlog_remove_profile_user_delete_settings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionlog',
            options={},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='class_name',
            new_name='student_class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(choices=[('Added', 'Added'), ('Edited', 'Edited'), ('Deleted', 'Deleted')], max_length=10),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
